### ISSUE TITLE
Support new elm 0.19

### ISSUE THREAD

**Issue by izderadicka** [hatzel/vorleser-web#18]
By default now elm 0.19 is installed and cannot compile this project easily (as project json structure has changed).  I update Makefile, which is relatively easy it was not enough.

**Comment by hatzel** [comment]
Sadly this is not an option without significant refactoring, as elm-mdl is no longer supported in 0.19, see: https://github.com/debois/elm-mdl/issues/377

**Comment by izderadicka** [comment]
OK, understood. I uninstalled 0.19 and installed 0.18 and now it's working fine.  
Then I would recommend to update readme - so people know instantly to install older elm version.
Maybe one small thing - in Makefile run use python3 command (python 2 does not have http.server module).
